AUTOCOMMIT OFF;

CREATE TABLE PERSON
   (
      ID   INTEGER NOT NULL,
      NAME VARCHAR(200) NOT NULL,
      CPF  INTEGER,
      CNPJ INTEGER,
      IERG INTEGER
   );


ALTER TABLE PERSON
   ADD CONSTRAINT PERSON_PK PRIMARY KEY (ID);

CREATE TABLE PHONE
   (
      ID        INTEGER NOT NULL,
      PERSON_ID INTEGER NOT NULL,
      "TYPE"    VARCHAR(20) NOT NULL,
      DDI       INTEGER NOT NULL,
      "NUMBER"  INTEGER NOT NULL
   );


ALTER TABLE PHONE
   ADD CONSTRAINT PHONE_PK PRIMARY KEY (ID, PERSON_ID);

ALTER TABLE PHONE
   ADD CONSTRAINT PHONE_ID_UNQ UNIQUE (ID);

CREATE TABLE ADRESS
   (
      ID        INTEGER NOT NULL,
      PERSON_ID INTEGER NOT NULL,
      ZIPCODE   INTEGER NOT NULL,
      ADRESS    VARCHAR(200) NOT NULL,
      CITY      VARCHAR(100) NOT NULL,
      REGION    VARCHAR(100) NOT NULL,
      COUNTRY   VARCHAR(100) NOT NULL
   );


ALTER TABLE ADRESS
   ADD CONSTRAINT ADRESS_PK PRIMARY KEY (ID, PERSON_ID);

ALTER TABLE ADRESS
   ADD CONSTRAINT ADRESS_ID_UNQ UNIQUE (ID);
